# Lead section
lead_title: "Construyamos algo que tus usuarios ❤️ usar."
lead_subtitle: "Somos una agencia de desarrollo de software especializados en Web y Mobile."
lead_btn:
  url: "/work"
  text: "Nuestro trabajo"

# Services section
services:
  title: "Esto es lo que podemos hacer por ti"
  web:
    title: "DESARROLLO WEB"
    text: "Nuestro proceso iterativo nos permite tener software funcional desde el día uno y continuar agregando funcionalidad cada semana, todo esto mientras mantenemos una comunicación constante contigo para priorizar hacer ajustes al roadmap."
    btn:
      text: "Metodología"
      url: "/process"
  mobile:
    title: "DESARROLLO DE APLICACIONES MÓVILES"
    text: "Usando React Native, construimos aplicaciones cross-platform para iOS y Android con una misma base de código. También por la flexibilidad que nos proporciona React Native, obtenemos un rendimiento y una velocidad de desarrollo increíbles."
    btn:
      text: "Servicios"
      url: "/services"
# Showcased Project section
showcased_project:
  brand:
    image: "/assets/img/logo-pleiq-primary.png"
    url: "#"
  title: "PleIQ es una compañia de Realidad Aumentada que esta creando experiencias educativas para ñiños de preescolar. Mira lo que hicimos para ellos."
  check_work:
    text: "Nuestro trabajo"
    url: "/work"

# Testimonies section
testimonies:
  - image: "/assets/img/picture-adrianna-tan.jpg"
    author: "Adrianna Tan"
    position: "CEO"
    company:
      url: "https://wobe.io"
      text: "Wobe"
    quote: '"They were our first team, pushed our MVP out of the door and helped our new hires to get up to speed. They work is outstanding."'
  - image: "/assets/img/picture-matt-ross.jpg"
    author: "Matt Ross"
    position: "PM"
    company:
      url: "https://fundingcircle.com/us"
      text: "Funding Circle"
    quote: "\"<b>Hash Labs</b> takes the time necessary to make sure their work is understood, documented and clearly communicated across all necessary channels. It was a pleasure to work with them.\""
