lead_title: "¡Esto es lo que podemos hacer por ti!"
lead_subtitle: "Somos especialistas en web y móvil"

offers:
  web_development:
    slug: "desktop"
    text: "Desarrollo Web"
    technologies:
      ruby_on_rails:
        text: "ruby on rails"
        href: "/services/ruby-on-rails"
      react:
        text: "react"
        href: "/services/react"
      go:
        text: "go"
        href: "/services/go"
  mobile_development:
    slug: "mobile"
    text: "Desarrollo Móvil"
    technologies:
      react_native:
        text: "react_native"
        href: "/services/react-native"

content_title: "Lorem ipsum dolor"
content_paragraph: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p><p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborumsed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>"
